#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit config file
server_config="
frontend  aflah_frontend
        bind *:80
        mode http
        default_backend aflah_backend
        timeout client 30s
        timeout connect 30s
        timeout server 30s
backend aflah_backend
        mode http
        balance roundrobin
        timeout client 30s
        timeout server 30s
        server 358420-web-01 34.224.16.126:80 check
        server 358420-web-02 54.237.34.32:80 check
"
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

# Testing the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
